name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create build dir
        run: mkdir build
      - name: Configure CMake
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${HOME}/.local -DCMAKE_C_FLAGS='-Wall -Wextra -pedantic'
        working-directory: ./build
      - name: Build and Install
        run: make -j2 && make install
        working-directory: ./build
      - name: Build and Run dumper
        run: |
          cmake -DCMAKE_PREFIX_PATH=${HOME}/.local &&
          make || ( echo 'Build failed' && exit 1 )
          cd ../data
          ../dumper/dumper b64zlib.tmx &&
          ../dumper/dumper --use-rc-mgr --fd tileset.tsx --callback pointtemplate.tx --buffer tiletemplate.tx objecttemplates.tmx
        working-directory: ./examples/dumper
      - name: Test C++ compatibility
        run: |
          cat > test.cpp <<EOF
            #include <tmx.h>
            int main(void) { tmx_map* map = tmx_load("map.tmx"); return 0; }
          EOF
          c++ -I src/ -c test.cpp
